Port Azure CI jobs to new GitHub Actions workflow
dlang/installer pull request #518
Opened 2022-07-24 09:58 UTC by kinke

2022-10-03 14:33 UTC, ibuclaw commented
@kinke who's going to be using this?

2022-10-05 13:55 UTC, Geod24 commented
Looks good! Can you rebase (and apply the diff from HEAD) so we can merge ?

2022-10-05 13:58 UTC, ibuclaw requested changes

2022-10-05 13:58 UTC, ibuclaw commented on .github/workflows/build_windows.yml
> +          powershell -command "& { iwr http://downloads.dlang.org/other/dm857c.zip -OutFile dmc.zip }"
https

2022-10-05 14:52 UTC, ibuclaw approved these changes

2022-10-05 14:56 UTC, ibuclaw commented
> Hmm, CI ran 2 months ago: https://github.com/dlang/installer/actions/workflows/build_windows.yml - not anymore apparently?

Not patient enough for the trigger to take effect. ;-)

2022-10-05 15:51 UTC, merged